### ISSUE TITLE
🐛 Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by nlsltz** [SAP/ui5-tooling#13]
## Expected Behavior
Should display the help

## Current Behavior
Command fails

## Steps to reproduce the issue
1. `npm install --global @ui5/cli`
2. `ui5 --help`

## Context
- OS/Platform: 64bit Mac OS X 10.13.5 17F77
- Shell: zsh 5.5.1
- Node.js Version: v9.6.1
- npm Version: 5.6.0

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [x] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Stack trace/log output
```sh
module.js:559
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nlsltz/.nvm/versions/node/v9.6.1/lib/node_modules/@ui5/cli/bin/ui5.js:2:13)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

**Comment by nlsltz** [comment]
Error message is gone after reinstalling the package.
