### ISSUE TITLE
ui5 serve https crash with 1.14.0

### ISSUE THREAD

**Issue by claussenj** [SAP/ui5-tooling#220]
##  Current Behavior
ui5 serve crashes when first https request arrives

## Steps to reproduce the issue
1. Let ui5 serve create certificates
2. re-launch ui5 with `ui5 serve --accept-remote-connections --h2`

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.14.0`
- OS/Platform: `Windows 10`
- Browser *(if relevant)*: `Chrome 80`

## Log Output / Stack Trace
```
$ ui5 serve --version
1.14.0 (from C:\Users\XXX\AppData\Roaming\npm\node_modules\@ui5\cli\bin\ui5.js)

$ ui5 serve --accept-remote-connections --h2
WARN types:application:ApplicationFormatter Failed to read manifest.json for project workload_analysis: ENOENT: no such file or directory, open 'C:\xxx\src\main\webapp\manifest.json'
Server started
URL: https://localhost:9443
internal/buffer.js:940
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:180:19)
    at Stream.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\@ui5\cli\node_modules\handle-thing\lib\handle.js:88:10)
    at Stream.emit (events.js:228:7)
    at endReadableNT (C:\Users\XXX\AppData\Roaming\npm\node_modules\@ui5\cli\node_modules\spdy-transport\node_modules\readable-stream\lib\_stream_readable.js:1094:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by codeworrior** [comment]
Sounds like a duplicate of https://github.com/SAP/ui5-server/issues/224 . 

What NodeJS version are you using?

**Comment by claussenj** [comment]
Yes, indeed related to the NodeJS version.
downgrade from 12.15 to 10.19 resolved the issue.
Sorry for missing the original issue!
