### ISSUE TITLE
project-shims : npm package loading issue

### ISSUE THREAD

**Issue by nbmedikonda** [SAP/ui5-tooling#275]
## Expected Behavior
it should work for all npm packages.

## Current Behavior
The build is failing if the npm module name starts with '@' in ui5.yaml 

https://www.npmjs.com/package/@okta/okta-signin-widget

**Package.json**
  "ui5": {
    "dependencies": [
      "xlsx",
      "@okta/okta-signin-widget"
    ]
  }

**ui5.yaml**

---
specVersion: "2.2"
kind: extension
type: project-shim
metadata:
  name: ahm.thirdparty
shims:
  configurations:
    @okta/okta-signin-widget:
      specVersion: "2.2"
      type: module
      metadata:
        name: @okta/okta-signin-widget
      resources:
        configuration:
          paths:
            /resources/thirdparty/okta: ' '

## Steps to reproduce the issue
configure the @okta/okta-signin-widget dependency as a UI5 project using a "Project Shim.

## Affected components *(if known)*

- [x ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```

**Comment by RandomByte** [comment]
> The build is failing

Hi @nbmedikonda, could you please share the error message you are facing as well as the connected log output?

**Comment by nbmedikonda** [comment]
@RandomByte  - 

Error Message:
Failed to parse configuration for project 'xyz at "/xyz/src/launchpad/ui5.yaml"
Error: bad indentation of a mapping entry in "/xyz/src/launchpad/ui5.yaml" at line 39, column 5:
        @okta/okta-signin-widget:
        ^

Stack Trace:
Error: Failed to parse configuration for project xyz at "/xyz/src/launchpad/ui5.yaml"
Error: bad indentation of a mapping entry in "/xyz/src/launchpad/ui5.yaml" at line 39, column 5:
        @okta/okta-signin-widget:
        ^
at ProjectPreprocessor.readConfigFile (/src/node_modules/@ui5/project/lib/projectPreprocessor.js:418:11)
    at async ProjectPreprocessor.loadProjectConfiguration (/src/node_modules/@ui5/project/lib/projectPreprocessor.js:212:19)
    at async /src/node_modules/@ui5/project/lib/projectPreprocessor.js:78:26
    at async Promise.all (index 0)
    at async ProjectPreprocessor.processTree (/src/node_modules/@ui5/project/lib/projectPreprocessor.js:62:4)
    at async Object.generateProjectTree (/src/node_modules/@ui5/project/lib/normalizer.js:33:10)
    at async Object.handleBuild [as handler] (/src/node_modules/@ui5/cli/lib/cli/commands/build.js:96:15)

**Comment by RandomByte** [comment]
According to the [YAML spec](https://yaml.org/spec/1.2/spec.html#id2772075), the `@`-sign is reserved for use as an "indicator". Therefore it must not come at the start of an **unquoted** string.

Please replace `@okta/okta-signin-widget` with `'@okta/okta-signin-widget'` to resolve this issue.

**Comment by jonaszuberbuehler** [comment]
@RandomByte Are you sure this resolves the issue? I'm facing the same problem here and using a string throws the following error:

`Invalid ui5.yaml configuration for project @okta/okta-signin-widget`

`Configuration property builder must not be provided here`

How can we fix this?

**Comment by RandomByte** [comment]
@jonaszuberbuehler please share your ui5.yaml. Double check the indentation of the `builder` configuration, if you have one.

**Comment by jonaszuberbuehler** [comment]
@RandomByte Thanks, the indentation is fine. The package I want to create a shim for is actually itself ui5 library project. The goal here is to have that shim copied over to the resource folder (with a custom task) but without all the ui5 framework libs. Maybe this is not the intended use case.
I've also checked the yaml file in the library project and it looks fine too (ui5 build runs w/o any issues). It has a builder configuration for transpiling the code only. Deleting that configuration fixes the mentioned error in the app project.

yaml of lib project:
```
specVersion: '2.2'
metadata:
  name: 'some-lib'
type: library
builder:
  customTasks:
    - name: transpile
      afterTask: replaceVersion
```

**Comment by RandomByte** [comment]
> Deleting that configuration fixes the mentioned error in the app project.

That's strange. Maybe the other project is using an older version of the UI5 CLI? Please check/share the verbose log of the command you are having issues with.

**Comment by jonaszuberbuehler** [comment]
It is using an older version of the UI5 cli. But updating it doesn't fix the problem unfortunately. Here's the log:

```
INFO: This project contains an individual @ui5/cli installation which will be used over the global one.
See https://github.com/SAP/ui5-cli#local-vs-global-installation for details.

verb cli:middlewares:base using @ui5/cli version 2.10.2 (from /Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/bin/ui5.js)
verb cli:middlewares:base using node version v12.14.0
verb normalizer:normalizer Building dependency tree...
verb normalizer:translators:npm Analyzing app (/Users/user/Documents/company/projects/foo/bar/app) (dependency of nothing - root project)
verb normalizer:translators:npm Ignoring npm dependency @ui5/cli. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/fs. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/logger. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency rimraf. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing @company/ui5.form-validation (/Users/user/Documents/company/ui5/form-validation) (dependency of app)
verb normalizer:translators:npm Ignoring npm dependency @sap/di.code-validation.js. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @sap/di.code-validation.xml. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/cli. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint-config-airbnb. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint-plugin-import. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint-plugin-jsx-a11y. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint-plugin-react. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency eslint-plugin-react-hooks. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency grunt. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency grunt-run. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-chrome-launcher. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-coverage. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-junit-reporter. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-ui5. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency rimraf. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing gs1-barcode-parser (/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser) (dependency of app)
verb normalizer:translators:npm Analyzing @company/ui5.copy-shims (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@company/ui5.copy-shims) (dependency of app)
verb normalizer:translators:npm Ignoring npm dependency @ui5/logger. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing @company/ui5-task-versioncommit (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@company/ui5-task-versioncommit) (dependency of app)
verb normalizer:translators:npm Ignoring npm dependency @ui5/builder. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/logger. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency nodegit. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing @sap/ux-ui5-tooling (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@sap/ux-ui5-tooling) (dependency of app)
verb normalizer:translators:npm Ignoring npm dependency @ui5/fs. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency express. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency livereload. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency update-notifier-webpack. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency keytar. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @sap/ux-app-templates. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @sap/ux-odata-client. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @types/body-parser. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @types/prompts. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @types/yazl. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/cli. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/project. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/server. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency body-parser. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency chalk. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency connect-livereload. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency dotenv. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency ejs. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency hasbin. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency http-proxy-agent. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency http-proxy-middleware. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency https-proxy-agent. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency i18next. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency mock-http-server. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency open. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency portfinder. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency prompts. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency serve-static. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency typescript. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency wait-for-expect. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency yaml. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency yargs-parser. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency yazl. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing @openui5/sap.m (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.m) (dependency of @company/ui5.form-validation)
verb normalizer:translators:npm Analyzing @company/ui5.transpile (/Users/user/Documents/company/ui5/form-validation/node_modules/@company/ui5.transpile) (dependency of @company/ui5.form-validation)
verb normalizer:translators:npm Ignoring npm dependency @babel/cli. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @babel/core. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @babel/plugin-transform-modules-commonjs. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @babel/preset-env. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency @ui5/logger. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.core) (dependency of @company/ui5.form-validation)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.core) (dependency of @openui5/sap.m)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.layout (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.layout) (dependency of @openui5/sap.m)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.unified (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.unified) (dependency of @openui5/sap.m)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.core) (dependency of @openui5/sap.ui.layout)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core (/Users/user/Documents/company/ui5/form-validation/node_modules/@openui5/sap.ui.core) (dependency of @openui5/sap.ui.unified)
verb normalizer:translators:npm [PERF] Consider defining UI5-dependencies in the package.json files of the relevant modules from the following list to improve npm translator execution time: gs1-barcode-parser, @openui5/sap.m, @openui5/sap.ui.core, @openui5/sap.ui.core, @openui5/sap.ui.layout, @openui5/sap.ui.unified, @openui5/sap.ui.core, @openui5/sap.ui.core
verb normalizer:translators:npm Treetop:
verb normalizer:translators:npm {
verb normalizer:translators:npm   id: 'app',
verb normalizer:translators:npm   version: '1.0.0-dev',
verb normalizer:translators:npm   path: '/Users/user/Documents/company/projects/foo/bar/app',
verb normalizer:translators:npm   dependencies: [
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: '@company/ui5.form-validation',
verb normalizer:translators:npm       version: '2.0.0',
verb normalizer:translators:npm       path: '/Users/user/Documents/company/ui5/form-validation',
verb normalizer:translators:npm       dependencies: [Array]
verb normalizer:translators:npm     },
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: 'gs1-barcode-parser',
verb normalizer:translators:npm       version: '1.0.1',
verb normalizer:translators:npm       path: '/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser',
verb normalizer:translators:npm       dependencies: []
verb normalizer:translators:npm     },
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: '@company/ui5-task-versioncommit',
verb normalizer:translators:npm       version: '1.1.1',
verb normalizer:translators:npm       path: '/Users/user/Documents/company/projects/foo/bar/app/node_modules/@company/ui5-task-versioncommit',
verb normalizer:translators:npm       dependencies: []
verb normalizer:translators:npm     },
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: '@company/ui5.copy-shims',
verb normalizer:translators:npm       version: '1.1.0',
verb normalizer:translators:npm       path: '/Users/user/Documents/company/projects/foo/bar/app/node_modules/@company/ui5.copy-shims',
verb normalizer:translators:npm       dependencies: []
verb normalizer:translators:npm     },
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: '@sap/ux-ui5-tooling',
verb normalizer:translators:npm       version: '1.1.5',
verb normalizer:translators:npm       path: '/Users/user/Documents/company/projects/foo/bar/app/node_modules/@sap/ux-ui5-tooling',
verb normalizer:translators:npm       dependencies: []
verb normalizer:translators:npm     }
verb normalizer:translators:npm   ]
verb normalizer:translators:npm }
verb normalizer:projectPreprocessor Processing project app on level 0...
verb normalizer:projectPreprocessor Processing dependency lookahead for app: @company/ui5.form-validation
verb normalizer:projectPreprocessor Processing dependency lookahead for app: gs1-barcode-parser
verb normalizer:projectPreprocessor Processing dependency lookahead for app: @company/ui5-task-versioncommit
verb normalizer:projectPreprocessor Processing dependency lookahead for app: @company/ui5.copy-shims
verb normalizer:projectPreprocessor Processing dependency lookahead for app: @sap/ux-ui5-tooling
verb normalizer:projectPreprocessor Failed to read configuration for project gs1-barcode-parser at "/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser/ui5.yaml". Error: ENOENT: no such file or directory, open '/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser/ui5.yaml'
verb normalizer:projectPreprocessor Applying extension ui5-task-versioncommit...
verb normalizer:projectPreprocessor Applying extension copy-shims...
verb normalizer:projectPreprocessor Applying extension fiori-tools-proxy...
verb normalizer:projectPreprocessor Applying extension fiori-tools-preview...
verb normalizer:projectPreprocessor Applying extension fiori-tools-servestatic...
verb normalizer:projectPreprocessor Applying extension deploy-to-abap...
verb normalizer:projectPreprocessor Applying extension fiori-tools-appreload...
verb normalizer:projectPreprocessor Applying extension app.thirdparty...
verb normalizer:projectPreprocessor Project shim app contains gs1-barcode-parser,@company/ui5.form-validation configuration(s)
verb normalizer:projectPreprocessor Project shim app: Adding project configuration for gs1-barcode-parser...
verb normalizer:projectPreprocessor Project shim app: Adding project configuration for @company/ui5.form-validation...
verb types:application:ApplicationFormatter Formatting application project app...
verb types:application:ApplicationFormatter Namespace of project app is com/foo/bar/app (from manifest.json)
verb normalizer:projectPreprocessor Processing project @company/ui5.form-validation on level 1...
verb normalizer:projectPreprocessor Processing dependency lookahead for @company/ui5.form-validation: @company/ui5.transpile
verb normalizer:projectPreprocessor Processing dependency lookahead for @company/ui5.form-validation: @openui5/sap.m
verb normalizer:projectPreprocessor Processing dependency lookahead for @company/ui5.form-validation: @openui5/sap.ui.core
verb normalizer:projectPreprocessor Processing project gs1-barcode-parser on level 1...
verb normalizer:projectPreprocessor Failed to read configuration for project gs1-barcode-parser at "/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser/ui5.yaml". Error: ENOENT: no such file or directory, open '/Users/user/Documents/company/projects/foo/bar/app/node_modules/gs1-barcode-parser/ui5.yaml'
verb normalizer:projectPreprocessor Applying configuration shim for project gs1-barcode-parser...
verb types:module:ModuleFormatter Formatting project gs1-barcode-parser...
verb normalizer:projectPreprocessor Applying extension transpile...
verb normalizer:projectPreprocessor Applying configuration shim for project @company/ui5.form-validation...

⚠️  Process Failed With Error

Error Message:
Invalid ui5.yaml configuration for project @company/ui5.form-validation

Configuration property builder must not be provided here

Stack Trace:
ValidationError: Invalid ui5.yaml configuration for project @company/ui5.form-validation

Configuration property builder must not be provided here
    at Validator.validate (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/validation/validator.js:43:10)
    at async validate (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/validation/validator.js:82:3)
    at async ProjectPreprocessor.validateAndNormalizeExistingProject (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:628:3)
    at async ProjectPreprocessor.applyShims (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:548:4)
    at async /Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:87:5
    at async Promise.all (index 0)
    at async ProjectPreprocessor.processTree (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:62:4)
    at async Object.generateProjectTree (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/node_modules/@ui5/project/lib/normalizer.js:34:10)
    at async Object.handleBuild [as handler] (/Users/user/Documents/company/projects/foo/bar/app/node_modules/@ui5/cli/lib/cli/commands/build.js:100:15)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose
```

**Comment by RandomByte** [comment]
Thanks Jonas. This log shows the error for a different module than in your first comment. "Invalid ui5.yaml configuration for project **`@okta/okta-signin-widget`**" vs. **`@company/ui5.form-validation`**. But in both cases it seems to be an issue with the configuration in the corresponding shim.

I think it's a different issue than the one reported here, which was caused by an unquoted, leading `@`-symbol.

The log indicates a problem with the configuration of `@company/ui5.form-validation`, after the shim configured in "`app`" has been applied.

Could you please share:
* the shim configuration contained in the ui5.yaml of your root project "`app`"
* the content of the ui5.yaml file in project `@company/ui5.form-validation`

Either one of them has bad configuration, or this is a bug with the shim application.

**Comment by jonaszuberbuehler** [comment]
True, it was initially the same problem (missing quotes around `@` symbol), but now it's a different issue.

The yaml for the `@compay/ui5.form-validation` is the one from above:
```
specVersion: '2.2'
metadata:
  name: 'form-validation'
type: library
builder:
  customTasks:
    - name: transpile
      afterTask: replaceVersion
```

Following is the yaml of the app project (minimal failing example):
```
specVersion: '2.2'
metadata:
  name: app
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: 'UTF-8'
---
specVersion: '2.2'
kind: extension
type: project-shim
metadata:
  name: app.thirdparty
shims:
  configurations:
    '@company/ui5.form-validation':
      specVersion: '2.2'
      type: module
      metadata:
        name: form-validation
      resources:
        configuration:
          paths:
            /resources/thirdparty/form-validation/: "./dist"
```
I'm using `ui5 build preload --clean-dest --include-task=generateManifestBundle generateCachebusterInfo` for building.

**Comment by RandomByte** [comment]
Alright, I think I know what's happening.

The ui5.yaml of `@compay/ui5.form-validation` defines type `library`, however this is overwritten with type `module` by the shim.

We don't really make it clear [in the documentation](https://sap.github.io/ui5-tooling/pages/Builder/#module), but there is no build for modules. Hence you are not allowed to configure custom tasks (or any other builder configuration).

Try using `type: library` in the shim configuration of `@company/ui5.form-validation`.

**Comment by RandomByte** [comment]
That's not really a problem with shims. Libraries have a strict path mapping configuration.

For libraries, you can't specify the target of the mapping. I.e. "src" is always mapped to `/resources/<namespace>` and "test" always to `/test-resources/<namespace>`.

For modules on the other hand, you can configure this freely.

See also: https://sap.github.io/ui5-tooling/pages/Configuration/#path-mapping

**Comment by jonaszuberbuehler** [comment]
Thanks for your reply! Adapting the paths fixes the problem.

Do you happen to know any useful resources for my problem concerning different versions of the same library deployed to ABAP repo? I didn't get any answer so far on slack.

**Comment by RandomByte** [comment]
> Do you happen to know any useful resources for my problem concerning different versions of the same library deployed to ABAP repo? I didn't get any answer so far on slack.

Sadly no. I guess you should either somehow deploy the library with different namespaces (which probably requires changing the namespace in almost all files) or find some solution to add your breaking changes to the library without actually breaking old consumers. Maybe add some versioning to the library itself? Like `my/library/name/v1/ModuleXyz.js`, `my/library/name/v2/ModuleXyz.js`, etc.
