### ISSUE TITLE
Error Unbound namespace prefix: "app" during build of cloud foundry app

### ISSUE THREAD

**Issue by LeaFries** [SAP/ui5-tooling#539]
## Expected Behavior
I've tried to build and deploy a cloud foundry app in Business Application Studio as well as locally on my Mac. Therefore I did the following steps in BAS:
- created an MTA project (Basic Multitarget Application)
- added an HTML5 Module (SAP Fiori application)
- followed the steps in "Adjust Your HTML5 Module" and "Build, Deploy, and Run your SAP Fiori Application" of this blog post: https://blogs.sap.com/2021/01/14/migrating-sap-fiori-applications-from-neo-to-cloud-foundry-using-sap-business-application-studio/ 
- downloaded the project from BAS and tried to build and deploy it locally; 

In BAS as well as locally, build of the app is failing.

## Current Behavior
When building the app in BAS (or locally), the error Unbound namespace prefix: "app" appears.

## Steps to Reproduce the Issue

1. Import project from `https://<internal-github>/<user>/qp-web-cf` in BAS or download it to run it locally.
2. BAS: Right-click on mta.yaml - Build MTA project
Local: run command `mbt build`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `2.11.1 (from /Users/<user>/.nvm/versions/node/v16.3.0/lib/node_modules/@ui5/cli/bin/ui5.js)`
 * Node.js Version: `v16.3.0`
 * npm Version: `7.15.1`
 * OS/Platform: `macOS Big Sur Version 11.4`
 * Browser *(if relevant)*: `Google Chrome`
 * cf -v: `cf version 7.2.0+be4a5ce2b.2020-12-10`
 * mbt -v: `Cloud MTA Build Tool version 1.2.1`

## Log Output / Stack Trace

```
> Executing task: mbt build -s '/home/user/projects/qp-web-cf'; sleep 2; <

[2021-07-20 13:44:19]  INFO Cloud MTA Build Tool version 1.1.0
[2021-07-20 13:44:19]  INFO generating the "Makefile_20210720134419.mta" file...
[2021-07-20 13:44:19]  INFO done
[2021-07-20 13:44:19]  INFO executing the "make -f Makefile_20210720134419.mta p=cf mtar= strict=true mode=" command...
[2021-07-20 13:44:19]  INFO validating the MTA project
[2021-07-20 13:44:19]  INFO validating the MTA project
[2021-07-20 13:44:19]  INFO building the "qp-web-cf-destination-content" module...
[2021-07-20 13:44:19]  INFO the "qp-web-cf-destination-content" module was not built because the "no-source" build parameter is set to "true"
[2021-07-20 13:44:19]  INFO finished building the "qp-web-cf-destination-content" module
[2021-07-20 13:44:19]  INFO building the "sapqpqpweb" module...
[2021-07-20 13:44:19]  INFO executing the "npm install" command...
........npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/@ui5/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 8.008s
.
53 packages are looking for funding
  run `npm fund` for details

[2021-07-20 13:44:28]  INFO executing the "npm run build:cf" command...

> qp-web@0.0.1 build:cf /home/user/projects/qp-web-cf/qp-web
> ui5 build preload --clean-dest --config ui5-deploy.yaml --include-task=generateManifestBundle generateCachebusterInfo

npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.16.0-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
..info builder:builder Building project sap.qp.qpweb not including dependencies...
info builder:builder 🛠  (1/1) Building project sap.qp.qpweb
.info builder:builder application sap.qp.qpweb 🔨 (1/12) Running task escapeNonAsciiCharacters...
info builder:builder application sap.qp.qpweb 🔨 (2/12) Running task replaceCopyright...
info builder:builder application sap.qp.qpweb 🔨 (3/12) Running task replaceVersion...
.info builder:builder application sap.qp.qpweb 🔨 (4/12) Running task generateFlexChangesBundle...
info builder:builder application sap.qp.qpweb 🔨 (5/12) Running task webide-extension-task-updateManifestJson...
info builder:builder application sap.qp.qpweb 🔨 (6/12) Running task generateManifestBundle...
info builder:builder application sap.qp.qpweb 🔨 (7/12) Running task generateComponentPreload...
(node:167) UnhandledPromiseRejectionWarning: Error: Unbound namespace prefix: "app"
Line: 18
Column: 86
Char: >
    at error (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/sax/lib/sax.js:677:7)
    at openTag (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/sax/lib/sax.js:810:11)
    at SAXParser.write (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/sax/lib/sax.js:1292:13)
    at Parser.exports.Parser.Parser.parseString (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/xml2js/lib/parser.js:5:59)
    at /home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:159:17
    at new Promise (<anonymous>)
    at XMLTemplateAnalyzer._analyze (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:158:10)
    at XMLTemplateAnalyzer.analyzeFragment (/home/user/projects/qp-web-cf/qp-web/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:143:15)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 333)
(node:167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
.info builder:builder application sap.qp.qpweb 🔨 (8/12) Running task createDebugFiles...
info builder:builder application sap.qp.qpweb 🔨 (9/12) Running task uglify...
info builder:builder application sap.qp.qpweb 🔨 (10/12) Running task generateVersionInfo...
info builder:builder application sap.qp.qpweb 🔨 (11/12) Running task generateCachebusterInfo...
info builder:builder application sap.qp.qpweb 🔨 (12/12) Running task ui5-task-zipper...
info builder:builder Build succeeded in 3.35 s
info builder:builder Executing cleanup tasks...
[2021-07-20 13:44:34]  INFO finished building the "sapqpqpweb" module
[2021-07-20 13:44:34]  INFO building the "qp-web-cf-app-content" module...
[2021-07-20 13:44:34]  INFO copying files matching the [sapqpqpweb.zip,...] patterns from the "/home/user/projects/qp-web-cf/qp-web/dist" folder to the "/home/user/projects/qp-web-cf/resources" folder
[2021-07-20 13:44:34]  INFO copying the "sapqpqpweb.zip" pattern from the "/home/user/projects/qp-web-cf/qp-web/dist" folder to the "/home/user/projects/qp-web-cf/resources" folder
[2021-07-20 13:44:34]  INFO the build results of the "qp-web-cf-app-content" module will be packaged and saved in the "/home/user/projects/qp-web-cf/.qp-web-cf_mta_build_tmp/qp-web-cf-app-content" folder
[2021-07-20 13:44:34]  INFO finished building the "qp-web-cf-app-content" module
[2021-07-20 13:44:34]  INFO generating the metadata...
[2021-07-20 13:44:34]  INFO generating the "/home/user/projects/qp-web-cf/.qp-web-cf_mta_build_tmp/META-INF/mtad.yaml" file...
[2021-07-20 13:44:34]  INFO generating the MTA archive...
[2021-07-20 13:44:34]  INFO the MTA archive generated at: /home/user/projects/qp-web-cf/mta_archives/qp-web-cf_0.0.1.mtar
[2021-07-20 13:44:34]  INFO cleaning temporary files...
```

**Comment by RandomByte** [comment]
Hi @LeaFries, Please refrain from posting SAP internal information on a public platform like github.com. I removed the offending information.

**Comment by RandomByte** [comment]
Thanks for reporting. The error message is really not helpful and should be improved.

This error is caused by the use of an undeclared namespace "app" in your file `QPTileContainer.fragment.xml`, line 11.  
To confirm this I removed the colon and executed the build command again, which succeeded.
