### ISSUE TITLE
Trouble running tutorial from ui5.sap.com

### ISSUE THREAD

**Issue by snovak** [SAP/ui5-tooling#649]
## Expected Behavior
Expected UI5 tool to build successfully.  

## Current Behavior
while I can eventually get `npm run start` to run as expected.....
`npm run build` fails with errors.

## Steps to Reproduce the Issue

1. Download example @ https://ui5.sap.com/#/entity/sap.ui.vk.tutorial.VIT/sample/sap.ui.vk.tutorial.VIT.05/
2. extract and cd in
3. `npm install`
4. at first `npm run start` fails, it wants a manifest.json in the project root, so I `cp src/manifest.json .`
5. `npm run start`, works... BUT
6. When I browse `http://localhost:8081/src/index.html` I get 404 on `sap.ui.core`. So, I link from CDN. 
7. Okay, now the app works in my local. 
8. `npm run build` 💥 not sure where to go from here.
9. log attached.
[log.txt](https://github.com/SAP/ui5-tooling/files/9570287/log.txt)

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **v16.14.0**
 * npm Version: **8.12.2**
 * OS/Platform: **12.15.1**
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

> sap.ui.vk.tutorial.VIT.05@1.0.0 build
> ui5 build

⚠️  Process Failed With Error

Error Message:
'return' outside of function

Stack Trace:
SyntaxError: 'return' outside of function
    at js_error (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:554:11)
    at croak (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:1278:9)
    at statement (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:1481:21)
    at _embed_tokens_wrapper (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:1343:26)
    at parse_toplevel (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:3526:23)
    at parse (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:3539:7)
    at Object.minify (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/terser/dist/bundle.min.js:29580:42)
    at BundleBuilder.compressJS (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/bundle/Builder.js:336:32)
    at BundleBuilder.writePreloadModule (/Users/i855307/Downloads/sap.ui.vk.tutorial.VIT.05/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/bundle/Builder.js:412:41)
    at runMicrotasks (<anonymous>)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose

**Comment by flovogt** [comment]
Hi @snovak, thanks a lot for bringing up this issue. There is already another one https://github.com/SAP/openui5/issues/3318 describing the same problem. Therefore, I'll close this issue here. We're working on it tracked by backlog items BGSOFUIPIRIN-5329 and CPOUI5FOUNDATION-378.
