### ISSUE TITLE
UI5 Tooling doesn't work when using debagger on BAS

### ISSUE THREAD

**Issue by ryoshib** [SAP/ui5-tooling#804]
## Current Behavior

Invalid Version: undefined

Stack Trace:
TypeError: Invalid Version: undefined
    at new SemVer (/home/user/projects/project2_using-realservice/node_modules/@sap/ux-ui5-tooling/dist/middlewares/fiori-tools-proxy.js:81209:17)
    at major2 (/home/user/projects/project2_using-realservice/node_modules/@sap/ux-ui5-tooling/dist/middlewares/fiori-tools-proxy.js:81540:32)
    at getNearestMaintenanceVersion (/home/user/projects/project2_using-realservice/node_modules/@sap/ux-ui5-tooling/dist/middlewares/fiori-tools-proxy.js:112164:90)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUI5Config (/home/user/projects/project2_using-realservice/node_modules/@sap/ux-ui5-tooling/dist/middlewares/fiori-tools-proxy.js:112375:20)
    at async module.exports (/home/user/projects/project2_using-realservice/node_modules/@sap/ux-ui5-tooling/dist/middlewares/fiori-tools-proxy.js:112428:50)
    at async MiddlewareManager.addMiddleware (file:///home/user/projects/project2_using-realservice/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:121:16)
    at async MiddlewareManager.addCustomMiddleware (file:///home/user/projects/project2_using-realservice/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:295:4)
    at async MiddlewareManager.applyMiddleware (file:///home/user/projects/project2_using-realservice/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:52:3)
    at async serve (file:///home/user/projects/project2_using-realservice/node_modules/@ui5/cli/node_modules/@ui5/server/lib/server.js:178:2)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose

**Comment by d3xter666** [comment]
HI @ryoshib ,

Could you elaborate a bit more? 

This seems like the version defined in `ui5 configuration of the fiori-tools-proxy` (@sap/ux-ui5-tooling/packages/ui5-tooling/src/middlewares/proxy/types.ts#L8)  is not in SemVer format: 

@sap/ux-ui5-tooling/packages/ui5-tooling/src/middlewares/proxy/utils.ts#L729
```ts
export interface UI5ProxyConfig {
    paths: PathConfig[];
    version?: string;
    directLoad?: boolean;
}
```

Would you be able to provide the ui5.yaml file where the @sap/ux-ui5-tooling proxy is configured?
