### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by Diwa-max** [SAP/ui5-tooling#849]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by flovogt** [comment]
Hi @Diwa-max, thanks for opening this issue. To process your request we need more information. Thx a lot

**Comment by Diwa-max** [comment]
info fiori-tools-proxy Using UI5 version 1.30 based on manifest.json

⚠️  Process Failed With Error

Error Message:
Invalid Version: 1.30

Stack Trace:
TypeError: Invalid Version: 1.30
    at new SemVer (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:42310:17)
    at compare (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:42671:65)
    at gt2 (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:42729:32)
    at C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:110248:79
    at Array.find (<anonymous>)
    at getNearestMaintenanceVersion (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:110248:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUI5Config (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:110460:20)
    at async module.exports (C:\Users\DiwakarB\Downloads\btp-extensions-unified-order-management-main\ui\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-proxy.js:110513:50)
    at async MiddlewareManager.addMiddleware (file:///C:/Users/DiwakarB/Downloads/btp-extensions-unified-order-management-main/ui/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:121:16)

**Comment by matz3** [comment]
The custom middleware `fiori-tools-proxy` is part of the `@sap/ux-ui5-tooling` module which is not part of the UI5 Tooling project (our modules all start with `@ui5/*`). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website (https://community.sap.com/topics/fiori-tools) or SAP Help Portal (https://help.sap.com/viewer/product/SAP_FIORI_tools).
