### ISSUE TITLE
Getting issue in UI5 tooling: middlewareUtil.getProject is not a function

### ISSUE THREAD

**Issue by pkgupta1008** [SAP/ui5-tooling#865]
<!--
Hey there 👋
Error Message:
middlewareUtil.getProject is not a function

Stack Trace:
TypeError: middlewareUtil.getProject is not a function
    at module.exports (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@sap\ux-ui5-tooling\dist\middlewares\fiori-tools-appreload.js:12168:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MiddlewareManager.addMiddleware (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:89:16)
    at async MiddlewareManager.addCustomMiddleware (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:237:4)
    at async MiddlewareManager.applyMiddleware (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:38:3)
    at async Object.serve (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@ui5\cli\node_modules\@ui5\server\lib\server.js:166:3)
    at async serve.handler (C:\Users\Prashanth\Desktop\vs\zibpprojections\node_modules\@ui5\cli\lib\cli\commands\serve.js:130:33)

**Comment by matz3** [comment]
Hey @pkgupta1008,

the `getProject` method on the `middlewareUtil` is only available when the ui5.yaml of the middleware extension defines `specVersion` 3.0 or above:

> This method is only available to custom server middleware extensions defining Specification Version 3.0 and above.

See: https://sap.github.io/ui5-tooling/v3/api/@ui5_server_middleware_MiddlewareUtil.html#getProject


This behaviour is mentioned in our [Custom Server Middleware documentation page](https://sap.github.io/ui5-tooling/stable/pages/extensibility/CustomServerMiddleware/#helper-class-middlewareutil).

I hope that this resolves the reported problem. If not, please share more details so that we can have another look.
